substitutions:
  min_brightness: "150"
  max_brightness: "700"
  warmup_brightness: "400"

esp8266:
  board: esp01_1m

uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 115200

status_led:
  pin: GPIO15

time:
  - platform: homeassistant
    id: ha_time

light:
  - platform: shelly_dimmer
    name: $devicename Light
    id: ${deviceid}_light
    power:
      id: ${deviceid}_power
      name: $devicename Light Power
    voltage:
      id: ${deviceid}_voltage
      name: $devicename Light Voltage
    current:
      id: ${deviceid}_current
      name: $devicename Light Current
    leading_edge: false
    min_brightness: $min_brightness
    max_brightness: $max_brightness
    warmup_brightness: $warmup_brightness
    firmware:
      version: "51.5"
      update: true

sensor:
  - platform: wifi_signal
    name: "$devicename WiFi Signal"
    update_interval: 60s

  - platform: ntc
    sensor: temp_resistance_reading
    name: ${devicename} Temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: "50.0"
        then:
          - light.turn_off: ${deviceid}_light
          
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
    
  - platform: adc
    id: temp_analog_reading
    pin: A0
    
  - platform: adc
    pin: VCC
    name: "$devicename VCC"

  - platform: total_daily_energy
    name: Daily Energy (Wh)
    id: ${deviceid}_daily_energy
    power_id: ${deviceid}_power
    unit_of_measurement: Wh
    device_class: energy
    state_class: total_increasing
